// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trx.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TrxObject struct {
	Height               *int32            `protobuf:"varint,1,req,name=height" json:"height,omitempty"`
	Vins                 []*TrxObject_VIN  `protobuf:"bytes,2,rep,name=vins" json:"vins,omitempty"`
	Vouts                []*TrxObject_VOUT `protobuf:"bytes,3,rep,name=vouts" json:"vouts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TrxObject) Reset()         { *m = TrxObject{} }
func (m *TrxObject) String() string { return proto.CompactTextString(m) }
func (*TrxObject) ProtoMessage()    {}
func (*TrxObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_trx_8bb324446f14073e, []int{0}
}
func (m *TrxObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxObject.Unmarshal(m, b)
}
func (m *TrxObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxObject.Marshal(b, m, deterministic)
}
func (dst *TrxObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxObject.Merge(dst, src)
}
func (m *TrxObject) XXX_Size() int {
	return xxx_messageInfo_TrxObject.Size(m)
}
func (m *TrxObject) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxObject.DiscardUnknown(m)
}

var xxx_messageInfo_TrxObject proto.InternalMessageInfo

func (m *TrxObject) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *TrxObject) GetVins() []*TrxObject_VIN {
	if m != nil {
		return m.Vins
	}
	return nil
}

func (m *TrxObject) GetVouts() []*TrxObject_VOUT {
	if m != nil {
		return m.Vouts
	}
	return nil
}

type TrxObject_VIN struct {
	Coinbase             *string  `protobuf:"bytes,1,opt,name=coinbase" json:"coinbase,omitempty"`
	Txid                 *string  `protobuf:"bytes,2,opt,name=txid" json:"txid,omitempty"`
	Vout                 *int32   `protobuf:"varint,3,opt,name=vout" json:"vout,omitempty"`
	Reserve              *string  `protobuf:"bytes,4,opt,name=reserve" json:"reserve,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrxObject_VIN) Reset()         { *m = TrxObject_VIN{} }
func (m *TrxObject_VIN) String() string { return proto.CompactTextString(m) }
func (*TrxObject_VIN) ProtoMessage()    {}
func (*TrxObject_VIN) Descriptor() ([]byte, []int) {
	return fileDescriptor_trx_8bb324446f14073e, []int{0, 0}
}
func (m *TrxObject_VIN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxObject_VIN.Unmarshal(m, b)
}
func (m *TrxObject_VIN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxObject_VIN.Marshal(b, m, deterministic)
}
func (dst *TrxObject_VIN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxObject_VIN.Merge(dst, src)
}
func (m *TrxObject_VIN) XXX_Size() int {
	return xxx_messageInfo_TrxObject_VIN.Size(m)
}
func (m *TrxObject_VIN) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxObject_VIN.DiscardUnknown(m)
}

var xxx_messageInfo_TrxObject_VIN proto.InternalMessageInfo

func (m *TrxObject_VIN) GetCoinbase() string {
	if m != nil && m.Coinbase != nil {
		return *m.Coinbase
	}
	return ""
}

func (m *TrxObject_VIN) GetTxid() string {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return ""
}

func (m *TrxObject_VIN) GetVout() int32 {
	if m != nil && m.Vout != nil {
		return *m.Vout
	}
	return 0
}

func (m *TrxObject_VIN) GetReserve() string {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return ""
}

type TrxObject_VOUT struct {
	Value                *string  `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	N                    *int32   `protobuf:"varint,2,req,name=n" json:"n,omitempty"`
	ScriptPubKey         *string  `protobuf:"bytes,3,req,name=scriptPubKey" json:"scriptPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrxObject_VOUT) Reset()         { *m = TrxObject_VOUT{} }
func (m *TrxObject_VOUT) String() string { return proto.CompactTextString(m) }
func (*TrxObject_VOUT) ProtoMessage()    {}
func (*TrxObject_VOUT) Descriptor() ([]byte, []int) {
	return fileDescriptor_trx_8bb324446f14073e, []int{0, 1}
}
func (m *TrxObject_VOUT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxObject_VOUT.Unmarshal(m, b)
}
func (m *TrxObject_VOUT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxObject_VOUT.Marshal(b, m, deterministic)
}
func (dst *TrxObject_VOUT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxObject_VOUT.Merge(dst, src)
}
func (m *TrxObject_VOUT) XXX_Size() int {
	return xxx_messageInfo_TrxObject_VOUT.Size(m)
}
func (m *TrxObject_VOUT) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxObject_VOUT.DiscardUnknown(m)
}

var xxx_messageInfo_TrxObject_VOUT proto.InternalMessageInfo

func (m *TrxObject_VOUT) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *TrxObject_VOUT) GetN() int32 {
	if m != nil && m.N != nil {
		return *m.N
	}
	return 0
}

func (m *TrxObject_VOUT) GetScriptPubKey() string {
	if m != nil && m.ScriptPubKey != nil {
		return *m.ScriptPubKey
	}
	return ""
}

func init() {
	proto.RegisterType((*TrxObject)(nil), "tutorial.TrxObject")
	proto.RegisterType((*TrxObject_VIN)(nil), "tutorial.TrxObject.VIN")
	proto.RegisterType((*TrxObject_VOUT)(nil), "tutorial.TrxObject.VOUT")
}

func init() { proto.RegisterFile("trx.proto", fileDescriptor_trx_8bb324446f14073e) }

var fileDescriptor_trx_8bb324446f14073e = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0xdd, 0x44, 0x9b, 0xb1, 0xa7, 0x41, 0x74, 0xe8, 0x29, 0xf4, 0x14, 0x10, 0xf6,
	0xe0, 0x5b, 0x14, 0x21, 0x95, 0xa5, 0xf6, 0x9e, 0xc4, 0xc5, 0xae, 0x94, 0x6c, 0xd9, 0xdd, 0x84,
	0xf8, 0x60, 0xbe, 0x9f, 0x64, 0x6a, 0x0b, 0x82, 0xb7, 0xf9, 0x7e, 0xbe, 0x9f, 0xe1, 0x87, 0x22,
	0x85, 0x49, 0x9f, 0x82, 0x4f, 0x1e, 0x17, 0x69, 0x48, 0x3e, 0xb8, 0xe6, 0xb8, 0xfe, 0x96, 0x50,
	0xec, 0xc2, 0xb4, 0x6d, 0x3f, 0x6d, 0x97, 0xf0, 0x01, 0x6e, 0x0e, 0xd6, 0x7d, 0x1c, 0x12, 0x89,
	0x52, 0x56, 0xb9, 0xf9, 0x25, 0x7c, 0x82, 0x6c, 0x74, 0x7d, 0x24, 0x59, 0xaa, 0xea, 0xee, 0xf9,
	0x51, 0x5f, 0xea, 0xfa, 0x5a, 0xd5, 0xfb, 0x4d, 0x6d, 0x58, 0x42, 0x0d, 0xf9, 0xe8, 0x87, 0x14,
	0x49, 0xb1, 0x4d, 0xff, 0xda, 0xdb, 0xb7, 0x9d, 0x39, 0x6b, 0xab, 0x0e, 0xd4, 0x7e, 0x53, 0xe3,
	0x0a, 0x16, 0x9d, 0x77, 0x7d, 0xdb, 0x44, 0x4b, 0xa2, 0x14, 0x55, 0x61, 0xae, 0x8c, 0x08, 0x59,
	0x9a, 0xdc, 0x3b, 0x49, 0xce, 0xf9, 0x9e, 0xb3, 0xb9, 0x4f, 0xaa, 0x14, 0x55, 0x6e, 0xf8, 0x46,
	0x82, 0xdb, 0x60, 0xa3, 0x0d, 0xa3, 0xa5, 0x8c, 0xd5, 0x0b, 0xae, 0x6a, 0xc8, 0xe6, 0x9f, 0x78,
	0x0f, 0xf9, 0xd8, 0x1c, 0x07, 0xcb, 0x03, 0x0b, 0x73, 0x06, 0x5c, 0x82, 0xe8, 0x49, 0xf2, 0x64,
	0xd1, 0xe3, 0x1a, 0x96, 0xb1, 0x0b, 0xee, 0x94, 0x5e, 0x87, 0xf6, 0xc5, 0x7e, 0x91, 0x62, 0xf5,
	0x4f, 0xf6, 0x13, 0x00, 0x00, 0xff, 0xff, 0x47, 0x7d, 0x35, 0x52, 0x4d, 0x01, 0x00, 0x00,
}
